Imported Required libraries

In [236]:
import pandas as pd
import numpy as np

Loading dataset

In [237]:
df=pd.read_csv('fifa.csv',encoding='latin-1')

Initial Data description

In [238]:
df.describe()

,sofifa_id,age,height_cm,weight_kg,league_rank,overall,potential,value_eur,wage_eur,international_reputation,...,mentality_penalties,mentality_composure,defending_marking,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes
count,18944.000000,18944.000000,18944.000000,18944.000000,18719.000000,18944.000000,18944.000000,1.894400e+04,18944.000000,18944.000000,...,18944.000000,18944.000000,0.0,18944.000000,18944.000000,18944.000000,18944.000000,18944.000000,18944.000000,18944.000000
mean,226242.402872,25.225823,181.190773,75.016892,1.357070,65.677787,71.086729,2.224813e+06,8675.852513,1.091850,...,48.050412,57.978674,NaN,47.581767,45.546505,16.446052,16.236486,16.103357,16.225982,16.551309
std,27171.091056,4.697354,6.825672,7.057140,0.739327,7.002278,6.109985,5.102486e+06,19654.774894,0.361841,...,15.671721,12.118390,NaN,21.402461,20.953997,17.577332,16.845480,16.519399,17.017341,17.878121
min,41.000000,16.000000,155.000000,50.000000,1.000000,47.000000,47.000000,0.000000e+00,0.000000,1.000000,...,6.000000,12.000000,NaN,5.000000,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,210030.500000,21.000000,176.000000,70.000000,1.000000,61.000000,67.000000,3.000000e+05,1000.000000,1.000000,...,38.750000,50.000000,NaN,27.000000,24.000000,8.000000,8.000000,8.000000,8.000000,8.000000
50%,232314.500000,25.000000,181.000000,75.000000,1.000000,66.000000,71.000000,6.500000e+05,3000.000000,1.000000,...,49.000000,59.000000,NaN,55.000000,52.000000,11.000000,11.000000,11.000000,11.000000,11.000000
75%,246760.250000,29.000000,186.000000,80.000000,1.000000,70.000000,75.000000,1.800000e+06,7000.000000,1.000000,...,60.000000,66.000000,NaN,65.000000,63.000000,14.000000,14.000000,14.000000,14.000000,14.000000
max,258970.000000,53.000000,206.000000,110.000000,4.000000,93.000000,95.000000,1.055000e+08,560000.000000,5.000000,...,92.000000,96.000000,NaN,93.000000,90.000000,90.000000,92.000000,93.000000,91.000000,90.000000

Spliting Date of Birth column into day,month and year

In [239]:
df[['day', 'month','year']] = df.dob.str.split("/", expand = True)

In [240]:
df

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club_name,...,rdm,rwb,lb,lcb,cb,rcb,rb,day,month,year
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,33,6/24/1987,170,72,Argentina,FC Barcelona,...,65+3,66+3,62+3,52+3,52+3,52+3,62+3,6,24,1987
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,35,2/5/1985,187,83,Portugal,Juventus,...,61+3,65+3,61+3,54+3,54+3,54+3,61+3,2,5,1985
2,200389,https://sofifa.com/player/200389/jan-oblak/210002,J. Oblak,Jan Oblak,27,1/7/1993,188,87,Slovenia,Atlético Madrid,...,36+3,32+3,32+3,33+3,33+3,33+3,32+3,1,7,1993
3,188545,https://sofifa.com/player/188545/robert-lewand...,R. Lewandowski,Robert Lewandowski,31,8/21/1988,184,80,Poland,FC Bayern München,...,65+3,64+3,61+3,60+3,60+3,60+3,61+3,8,21,1988
4,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Júnior,28,2/5/1992,175,68,Brazil,Paris Saint-Germain,...,62+3,67+3,62+3,49+3,49+3,49+3,62+3,2,5,1992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18939,256679,https://sofifa.com/player/256679/kevin-angulo/...,K. Angulo,Kevin Angulo,24,4/13/1996,176,73,Colombia,América de Cali,...,47+2,47+2,47+2,46+2,46+2,46+2,47+2,4,13,1996
18940,257710,https://sofifa.com/player/257710/mengxuan-zhan...,Zhang Mengxuan,Mengxuan Zhang,21,4/26/1999,177,70,China PR,Chongqing Dangdai Lifan FC SWM Team,...,41+2,42+2,45+2,47+2,47+2,47+2,45+2,4,26,1999
18941,250989,https://sofifa.com/player/250989/zhenghao-wang...,Wang Zhenghao,???,20,6/28/2000,185,74,China PR,Tianjin TEDA FC,...,42+2,42+2,44+2,47+2,47+2,47+2,44+2,6,28,2000
18942,257697,https://sofifa.com/player/257697/zitong-chen/2...,Chen Zitong,Zitong Chen,23,2/20/1997,186,80,China PR,Shijiazhuang Ever Bright F.C.,...,49+2,47+2,47+2,49+2,49+2,49+2,47+2,2,20,1997
18943,257936,https://sofifa.com/player/257936/yue-song/210002,Song Yue,Yue Song,28,11/20/1991,185,79,China PR,Tianjin TEDA FC,...,47+0,47+0,47+0,46+1,46+1,46+1,47+0,11,20,1991

Dropping DOB column

In [241]:
df=df.drop('dob',axis=1)

In [242]:
df

,sofifa_id,player_url,short_name,long_name,age,height_cm,weight_kg,nationality,club_name,league_name,...,rdm,rwb,lb,lcb,cb,rcb,rb,day,month,year
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,33,170,72,Argentina,FC Barcelona,Spain Primera Division,...,65+3,66+3,62+3,52+3,52+3,52+3,62+3,6,24,1987
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,35,187,83,Portugal,Juventus,Italian Serie A,...,61+3,65+3,61+3,54+3,54+3,54+3,61+3,2,5,1985
2,200389,https://sofifa.com/player/200389/jan-oblak/210002,J. Oblak,Jan Oblak,27,188,87,Slovenia,Atlético Madrid,Spain Primera Division,...,36+3,32+3,32+3,33+3,33+3,33+3,32+3,1,7,1993
3,188545,https://sofifa.com/player/188545/robert-lewand...,R. Lewandowski,Robert Lewandowski,31,184,80,Poland,FC Bayern München,German 1. Bundesliga,...,65+3,64+3,61+3,60+3,60+3,60+3,61+3,8,21,1988
4,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Júnior,28,175,68,Brazil,Paris Saint-Germain,French Ligue 1,...,62+3,67+3,62+3,49+3,49+3,49+3,62+3,2,5,1992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18939,256679,https://sofifa.com/player/256679/kevin-angulo/...,K. Angulo,Kevin Angulo,24,176,73,Colombia,América de Cali,Colombian Liga Postobón,...,47+2,47+2,47+2,46+2,46+2,46+2,47+2,4,13,1996
18940,257710,https://sofifa.com/player/257710/mengxuan-zhan...,Zhang Mengxuan,Mengxuan Zhang,21,177,70,China PR,Chongqing Dangdai Lifan FC SWM Team,Chinese Super League,...,41+2,42+2,45+2,47+2,47+2,47+2,45+2,4,26,1999
18941,250989,https://sofifa.com/player/250989/zhenghao-wang...,Wang Zhenghao,???,20,185,74,China PR,Tianjin TEDA FC,Chinese Super League,...,42+2,42+2,44+2,47+2,47+2,47+2,44+2,6,28,2000
18942,257697,https://sofifa.com/player/257697/zitong-chen/2...,Chen Zitong,Zitong Chen,23,186,80,China PR,Shijiazhuang Ever Bright F.C.,Chinese Super League,...,49+2,47+2,47+2,49+2,49+2,49+2,47+2,2,20,1997
18943,257936,https://sofifa.com/player/257936/yue-song/210002,Song Yue,Yue Song,28,185,79,China PR,Tianjin TEDA FC,Chinese Super League,...,47+0,47+0,47+0,46+1,46+1,46+1,47+0,11,20,1991

Dropping unnecessary columns

In [243]:
df=df.drop(['st','rs',	'lw',	'lf',	'cf',	'rf',	'rw',	'lam',	'cam',	'ram',	'lm',	'lcm',	'cm',	'rcm',	'rm',	'lwb',	'ldm',	'cdm',	'rdm','defending_marking',	'rwb',	'lb',	'lcb',	'cb',	'rcb',	'rb'],axis=1)

Dealing with empty rows
Identifying all the columns where datatype is integer or float; so that missing values could be handel by mean values

In [244]:
int_flt_columns = df.select_dtypes(include=['int', 'float']).columns
int_flt_columns

Index(['sofifa_id', 'age', 'height_cm', 'weight_kg', 'league_rank', 'overall',
       'potential', 'value_eur', 'wage_eur', 'international_reputation',
       'weak_foot', 'skill_moves', 'release_clause_eur', 'team_jersey_number',
       'contract_valid_until', 'nation_jersey_number', 'pace', 'shooting',
       'passing', 'dribbling', 'defending', 'physic', 'gk_diving',
       'gk_handling', 'gk_kicking', 'gk_reflexes', 'gk_speed',
       'gk_positioning', 'attacking_crossing', 'attacking_finishing',
       'attacking_heading_accuracy', 'attacking_short_passing',
       'attacking_volleys', 'skill_dribbling', 'skill_curve',
       'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control',
       'movement_acceleration', 'movement_sprint_speed', 'movement_agility',
       'movement_reactions', 'movement_balance', 'power_shot_power',
       'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots',
       'mentality_aggression', 'mentality_interceptions',
       'mentality_positioning', 'mentality_vision', 'mentality_penalties',
       'mentality_composure', 'defending_standing_tackle',
       'defending_sliding_tackle', 'goalkeeping_diving',
       'goalkeeping_handling', 'goalkeeping_kicking',
       'goalkeeping_positioning', 'goalkeeping_reflexes'],
      dtype='object')

Defining a function to deal with missing values

In [245]:
 def missing_values(col_list):
  for column in col_list:
    if column in df.columns:
        if df[column].isnull().any():
            column_mean = df[column].mean()
            df[column].fillna(column_mean, inplace=True)
            print(f"Filled null values in '{column}' with mean value: {column_mean}")
        else:
            print(f"No null values found in '{column}'")
    else:
        print(f"'{column}' not found in the DataFrame")

# Display the DataFrame after filling null values
print("\nDataFrame after filling null values:")
print(df)

DataFrame after filling null values:
       sofifa_id                                         player_url  \
0         158023  https://sofifa.com/player/158023/lionel-messi/...
1          20801  https://sofifa.com/player/20801/c-ronaldo-dos-...
2         200389  https://sofifa.com/player/200389/jan-oblak/210002
3         188545  https://sofifa.com/player/188545/robert-lewand...
4         190871  https://sofifa.com/player/190871/neymar-da-sil...
...          ...                                                ...
18939     256679  https://sofifa.com/player/256679/kevin-angulo/...
18940     257710  https://sofifa.com/player/257710/mengxuan-zhan...
18941     250989  https://sofifa.com/player/250989/zhenghao-wang...
18942     257697  https://sofifa.com/player/257697/zitong-chen/2...
18943     257936   https://sofifa.com/player/257936/yue-song/210002

              short_name                            long_name  age  height_cm  \
0               L. Messi       Lionel Andrés Messi Cuccittini   33        170
1      Cristiano Ronaldo  Cristiano Ronaldo dos Santos Aveiro   35        187
2               J. Oblak                            Jan Oblak   27        188
3         R. Lewandowski                   Robert Lewandowski   31        184
4              Neymar Jr        Neymar da Silva Santos Júnior   28        175
...                  ...                                  ...  ...        ...
18939          K. Angulo                         Kevin Angulo   24        176
18940     Zhang Mengxuan                       Mengxuan Zhang   21        177
18941      Wang Zhenghao                                  ???   20        185
18942        Chen Zitong                          Zitong Chen   23        186
18943           Song Yue                             Yue Song   28        185

       weight_kg nationality                            club_name  \
0             72   Argentina                         FC Barcelona
1             83    Portugal                             Juventus
2             87    Slovenia                      Atlético Madrid
3             80      Poland                    FC Bayern München
4             68      Brazil                  Paris Saint-Germain
...          ...         ...                                  ...
18939         73    Colombia                      América de Cali
18940         70    China PR  Chongqing Dangdai Lifan FC SWM Team
18941         74    China PR                      Tianjin TEDA FC
18942         80    China PR        Shijiazhuang Ever Bright F.C.
18943         79    China PR                      Tianjin TEDA FC

                   league_name  ...  defending_sliding_tackle  \
0       Spain Primera Division  ...                        24
1              Italian Serie A  ...                        24
2       Spain Primera Division  ...                        18
3         German 1. Bundesliga  ...                        19
4               French Ligue 1  ...                        29
...                        ...  ...                       ...
18939  Colombian Liga Postobón  ...                        54
18940     Chinese Super League  ...                        47
18941     Chinese Super League  ...                        45
18942     Chinese Super League  ...                        45
18943     Chinese Super League  ...                        45

       goalkeeping_diving  goalkeeping_handling  goalkeeping_kicking  \
0                       6                    11                   15
1                       7                    11                   15
2                      87                    92                   78
3                      15                     6                   12
4                       9                     9                   15
...                   ...                   ...                  ...
18939                  10                     9                   14
18940                  12                    13                    8
18941                  12                     9                   14
18942                  15                     7                    7
18943                   8                     5                   11

       goalkeeping_positioning goalkeeping_reflexes    ls  day  month  year
0                           14                    8  89+3    6     24  1987
1                           14                   11  91+1    2      5  1985
2                           90                   90  33+3    1      7  1993
3                            8                   10  89+2    8     21  1988
4                           15                   11  84+3    2      5  1992
...                        ...                  ...   ...  ...    ...   ...
18939                        6                    6  44+2    4     13  1996
18940                       14                    6  32+2    4     26  1999
18941                       15                   13  34+2    6     28  2000
18942                        5                   13  44+2    2     20  1997
18943                        5                    7  46+1   11     20  1991

[18944 rows x 82 columns]

In [246]:
missing_values(int_flt_columns)

No null values found in 'sofifa_id'
No null values found in 'age'
No null values found in 'height_cm'
No null values found in 'weight_kg'
Filled null values in 'league_rank' with mean value: 1.357070356322453
No null values found in 'overall'
No null values found in 'potential'
No null values found in 'value_eur'
No null values found in 'wage_eur'
No null values found in 'international_reputation'
No null values found in 'weak_foot'
No null values found in 'skill_moves'
Filled null values in 'release_clause_eur' with mean value: 4296353.05588055
Filled null values in 'team_jersey_number' with mean value: 20.589668251509163
Filled null values in 'contract_valid_until' with mean value: 2021.9833324429724
Filled null values in 'nation_jersey_number' with mean value: 12.029281277728483
Filled null values in 'pace' with mean value: 67.66810983927407
Filled null values in 'shooting' with mean value: 52.27495403594093
Filled null values in 'passing' with mean value: 57.13943419725995
Filled null values in 'dribbling' with mean value: 62.45542968981674
Filled null values in 'defending' with mean value: 51.31629203487338
Filled null values in 'physic' with mean value: 64.4589881976158
Filled null values in 'gk_diving' with mean value: 65.16418626980317
Filled null values in 'gk_handling' with mean value: 62.88910225636102
Filled null values in 'gk_kicking' with mean value: 61.71963514162266
Filled null values in 'gk_reflexes' with mean value: 66.10801728276525
Filled null values in 'gk_speed' with mean value: 37.20355256841095
Filled null values in 'gk_positioning' with mean value: 63.171867498799806
No null values found in 'attacking_crossing'
No null values found in 'attacking_finishing'
No null values found in 'attacking_heading_accuracy'
No null values found in 'attacking_short_passing'
No null values found in 'attacking_volleys'
No null values found in 'skill_dribbling'
No null values found in 'skill_curve'
No null values found in 'skill_fk_accuracy'
No null values found in 'skill_long_passing'
No null values found in 'skill_ball_control'
No null values found in 'movement_acceleration'
No null values found in 'movement_sprint_speed'
No null values found in 'movement_agility'
No null values found in 'movement_reactions'
No null values found in 'movement_balance'
No null values found in 'power_shot_power'
No null values found in 'power_jumping'
No null values found in 'power_stamina'
No null values found in 'power_strength'
No null values found in 'power_long_shots'
No null values found in 'mentality_aggression'
No null values found in 'mentality_interceptions'
No null values found in 'mentality_positioning'
No null values found in 'mentality_vision'
No null values found in 'mentality_penalties'
No null values found in 'mentality_composure'
No null values found in 'defending_standing_tackle'
No null values found in 'defending_sliding_tackle'
No null values found in 'goalkeeping_diving'
No null values found in 'goalkeeping_handling'
No null values found in 'goalkeeping_kicking'
No null values found in 'goalkeeping_positioning'
No null values found in 'goalkeeping_reflexes'

In [247]:
 df.select_dtypes(include=['int','float']).isnull().any()

sofifa_id                  False
age                        False
height_cm                  False
weight_kg                  False
league_rank                False
                           ...
goalkeeping_diving         False
goalkeeping_handling       False
goalkeeping_kicking        False
goalkeeping_positioning    False
goalkeeping_reflexes       False
Length: 61, dtype: bool

Recheck

In [248]:
empty_rows = int_flt_columns.isnull()

# Display the empty rows
print(empty_rows)

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False]

In [249]:
df

,sofifa_id,player_url,short_name,long_name,age,height_cm,weight_kg,nationality,club_name,league_name,...,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,ls,day,month,year
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,33,170,72,Argentina,FC Barcelona,Spain Primera Division,...,24,6,11,15,14,8,89+3,6,24,1987
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,35,187,83,Portugal,Juventus,Italian Serie A,...,24,7,11,15,14,11,91+1,2,5,1985
2,200389,https://sofifa.com/player/200389/jan-oblak/210002,J. Oblak,Jan Oblak,27,188,87,Slovenia,Atlético Madrid,Spain Primera Division,...,18,87,92,78,90,90,33+3,1,7,1993
3,188545,https://sofifa.com/player/188545/robert-lewand...,R. Lewandowski,Robert Lewandowski,31,184,80,Poland,FC Bayern München,German 1. Bundesliga,...,19,15,6,12,8,10,89+2,8,21,1988
4,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Júnior,28,175,68,Brazil,Paris Saint-Germain,French Ligue 1,...,29,9,9,15,15,11,84+3,2,5,1992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18939,256679,https://sofifa.com/player/256679/kevin-angulo/...,K. Angulo,Kevin Angulo,24,176,73,Colombia,América de Cali,Colombian Liga Postobón,...,54,10,9,14,6,6,44+2,4,13,1996
18940,257710,https://sofifa.com/player/257710/mengxuan-zhan...,Zhang Mengxuan,Mengxuan Zhang,21,177,70,China PR,Chongqing Dangdai Lifan FC SWM Team,Chinese Super League,...,47,12,13,8,14,6,32+2,4,26,1999
18941,250989,https://sofifa.com/player/250989/zhenghao-wang...,Wang Zhenghao,???,20,185,74,China PR,Tianjin TEDA FC,Chinese Super League,...,45,12,9,14,15,13,34+2,6,28,2000
18942,257697,https://sofifa.com/player/257697/zitong-chen/2...,Chen Zitong,Zitong Chen,23,186,80,China PR,Shijiazhuang Ever Bright F.C.,Chinese Super League,...,45,15,7,7,5,13,44+2,2,20,1997
18943,257936,https://sofifa.com/player/257936/yue-song/210002,Song Yue,Yue Song,28,185,79,China PR,Tianjin TEDA FC,Chinese Super League,...,45,8,5,11,5,7,46+1,11,20,1991

identifying the datatype for rest of the columns

In [250]:
for column_name, dtype in df.dtypes.items():
    print(f"Column: {column_name}, Data Type: {dtype}")

Column: sofifa_id, Data Type: int64
Column: player_url, Data Type: object
Column: short_name, Data Type: object
Column: long_name, Data Type: object
Column: age, Data Type: int64
Column: height_cm, Data Type: int64
Column: weight_kg, Data Type: int64
Column: nationality, Data Type: object
Column: club_name, Data Type: object
Column: league_name, Data Type: object
Column: league_rank, Data Type: float64
Column: overall, Data Type: int64
Column: potential, Data Type: int64
Column: value_eur, Data Type: int64
Column: wage_eur, Data Type: int64
Column: player_positions, Data Type: object
Column: preferred_foot, Data Type: object
Column: international_reputation, Data Type: int64
Column: weak_foot, Data Type: int64
Column: skill_moves, Data Type: int64
Column: work_rate, Data Type: object
Column: body_type, Data Type: object
Column: real_face, Data Type: object
Column: release_clause_eur, Data Type: float64
Column: player_tags, Data Type: object
Column: team_position, Data Type: object
Column: team_jersey_number, Data Type: float64
Column: loaned_from, Data Type: object
Column: joined, Data Type: object
Column: contract_valid_until, Data Type: float64
Column: nation_position, Data Type: object
Column: nation_jersey_number, Data Type: float64
Column: pace, Data Type: float64
Column: shooting, Data Type: float64
Column: passing, Data Type: float64
Column: dribbling, Data Type: float64
Column: defending, Data Type: float64
Column: physic, Data Type: float64
Column: gk_diving, Data Type: float64
Column: gk_handling, Data Type: float64
Column: gk_kicking, Data Type: float64
Column: gk_reflexes, Data Type: float64
Column: gk_speed, Data Type: float64
Column: gk_positioning, Data Type: float64
Column: player_traits, Data Type: object
Column: attacking_crossing, Data Type: int64
Column: attacking_finishing, Data Type: int64
Column: attacking_heading_accuracy, Data Type: int64
Column: attacking_short_passing, Data Type: int64
Column: attacking_volleys, Data Type: int64
Column: skill_dribbling, Data Type: int64
Column: skill_curve, Data Type: int64
Column: skill_fk_accuracy, Data Type: int64
Column: skill_long_passing, Data Type: int64
Column: skill_ball_control, Data Type: int64
Column: movement_acceleration, Data Type: int64
Column: movement_sprint_speed, Data Type: int64
Column: movement_agility, Data Type: int64
Column: movement_reactions, Data Type: int64
Column: movement_balance, Data Type: int64
Column: power_shot_power, Data Type: int64
Column: power_jumping, Data Type: int64
Column: power_stamina, Data Type: int64
Column: power_strength, Data Type: int64
Column: power_long_shots, Data Type: int64
Column: mentality_aggression, Data Type: int64
Column: mentality_interceptions, Data Type: int64
Column: mentality_positioning, Data Type: int64
Column: mentality_vision, Data Type: int64
Column: mentality_penalties, Data Type: int64
Column: mentality_composure, Data Type: int64
Column: defending_standing_tackle, Data Type: int64
Column: defending_sliding_tackle, Data Type: int64
Column: goalkeeping_diving, Data Type: int64
Column: goalkeeping_handling, Data Type: int64
Column: goalkeeping_kicking, Data Type: int64
Column: goalkeeping_positioning, Data Type: int64
Column: goalkeeping_reflexes, Data Type: int64
Column: ls, Data Type: object
Column: day, Data Type: object
Column: month, Data Type: object
Column: year, Data Type: object

identifying column with object datatype consisting null values

In [251]:

object_columns_with_nulls = df.select_dtypes(include=['object']).columns[df.select_dtypes(include=['object']).isnull().any()]
object_columns_with_nulls

Index(['club_name', 'league_name', 'player_tags', 'team_position',
       'loaned_from', 'joined', 'nation_position', 'player_traits'],
      dtype='object')

Filling all null values with their respective mode

In [252]:
for column in object_columns_with_nulls:
    mode_value = df[column].mode()[0]  # Get the mode value
    df[column].fillna(mode_value, inplace=True)

Recheck

In [253]:
object_columns_with_nulls = df.select_dtypes(include=['object']).isnull().any()
object_columns_with_nulls

player_url          False
short_name          False
long_name           False
nationality         False
club_name           False
league_name         False
player_positions    False
preferred_foot      False
work_rate           False
body_type           False
real_face           False
player_tags         False
team_position       False
loaned_from         False
joined              False
nation_position     False
player_traits       False
ls                  False
day                 False
month               False
year                False
dtype: bool

Datatype conversion

In [254]:
#df[['value_eur']] = df[['value_eur']].astype(int)

Changing the datatype of few columns

In [255]:
clm=df[['value_eur','release_clause_eur','wage_eur']]

In [256]:
def type_change(x):

  for x in clm:
   df[x]=df[x].astype(int)

In [257]:
df['release_clause_eur'].isnull().sum()

0

In [258]:
type_change('release_clause_eur')

ReCheck

In [259]:
for x in clm:
 y=df[x].dtype
 print(y)

int64
int64
int64

In [260]:
df

,sofifa_id,player_url,short_name,long_name,age,height_cm,weight_kg,nationality,club_name,league_name,...,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,ls,day,month,year
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,33,170,72,Argentina,FC Barcelona,Spain Primera Division,...,24,6,11,15,14,8,89+3,6,24,1987
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,35,187,83,Portugal,Juventus,Italian Serie A,...,24,7,11,15,14,11,91+1,2,5,1985
2,200389,https://sofifa.com/player/200389/jan-oblak/210002,J. Oblak,Jan Oblak,27,188,87,Slovenia,Atlético Madrid,Spain Primera Division,...,18,87,92,78,90,90,33+3,1,7,1993
3,188545,https://sofifa.com/player/188545/robert-lewand...,R. Lewandowski,Robert Lewandowski,31,184,80,Poland,FC Bayern München,German 1. Bundesliga,...,19,15,6,12,8,10,89+2,8,21,1988
4,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Júnior,28,175,68,Brazil,Paris Saint-Germain,French Ligue 1,...,29,9,9,15,15,11,84+3,2,5,1992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18939,256679,https://sofifa.com/player/256679/kevin-angulo/...,K. Angulo,Kevin Angulo,24,176,73,Colombia,América de Cali,Colombian Liga Postobón,...,54,10,9,14,6,6,44+2,4,13,1996
18940,257710,https://sofifa.com/player/257710/mengxuan-zhan...,Zhang Mengxuan,Mengxuan Zhang,21,177,70,China PR,Chongqing Dangdai Lifan FC SWM Team,Chinese Super League,...,47,12,13,8,14,6,32+2,4,26,1999
18941,250989,https://sofifa.com/player/250989/zhenghao-wang...,Wang Zhenghao,???,20,185,74,China PR,Tianjin TEDA FC,Chinese Super League,...,45,12,9,14,15,13,34+2,6,28,2000
18942,257697,https://sofifa.com/player/257697/zitong-chen/2...,Chen Zitong,Zitong Chen,23,186,80,China PR,Shijiazhuang Ever Bright F.C.,Chinese Super League,...,45,15,7,7,5,13,44+2,2,20,1997
18943,257936,https://sofifa.com/player/257936/yue-song/210002,Song Yue,Yue Song,28,185,79,China PR,Tianjin TEDA FC,Chinese Super League,...,45,8,5,11,5,7,46+1,11,20,1991